### PR TITLE
Only allow regex to start with valid SVG tags

### PR DESCRIPTION
**Pull request by kevva**
This could require a major since it'll break in some places where people expects false positives for some reason.

Still won't allow for comments though.

Fixes #2.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you also add to the readme about what cases it won't be able to handle, per #2?

**Comment by kevva** [comment]
Added.

**Comment by kevva** [comment]
:+1:

**Comment by sindresorhus** [comment]
Looks good! Thanks Kevin :)

Re comments. Couldn't we just do a regex to strip them out before testing the string?

**Comment by kevva** [comment]
Sure, that sounds reasonable. Here's one I found, https://github.com/stevemao/html-comment-regex.

**Comment by sindresorhus** [comment]
👍 Go for it.

**Pull request merged**
